version: '3'
services:
  web-app:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=development
      - COMMAND_TO_RUN=start:dev
    depends_on:
      - postgres-db
    networks:
      - budget_buddy_network

  postgres-db:
    image: postgres:14
    ports: 
      - '5432:5432'
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - budget_buddy_network

networks:
  budget_buddy_network:
    driver: bridge

volumes:
  postgres_data: